version: '3.7'
services:
    api:
        container_name: api
        build: .
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8700"
        restart: always
        volumes:
            - .:/api
        ports:
            - "8700:8700"
        networks:
            proxy:
        
        

    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        
        ports:
            - "3000:3000"

        networks:
            proxy:

    api-server:
        container_name: api-server
        restart: always
        build: ./nginx
        ports:
            - 80:80
            - 443:443
        depends_on:
            - api
        networks:
            proxy:
        volumes:
            - ./static:/home/app/web/static
            - ./media:/home/app/web/media
            - ./nginx/conf/:/etc/nginx/conf.d/:ro
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/nginx/ssl/:ro
    memcached:
        container_name: memcached
        image: memcached:latest
        restart: always
        ports:
            - 11211
        networks:
            - proxy
    
    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
    proxy:
        name: proxy